---
# tasks file for aur
- name: Create aur_builder user
  user:
    name: aur_builder
    group: wheel
  become: yes

- name: Create sudo rights for aur_builder user
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  become: yes

- name: Install oh-my-zsh via aur
  aur: name=oh-my-zsh-git use=makepkg state=present
  become: yes
  become_user: aur_builder

- name: define the default shell
  user:
    name: "{{ansible_env.USER}}"
    shell: "/usr/bin/{{default_shell}}"
  become: true

- name: Download custom plugin Zsh-syntax-highlighting
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting'
    dest: /usr/share/oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    clone: yes
    update: yes
  become: true

- name: Download custom plugin Zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: /usr/share/oh-my-zsh/custom/plugins/zsh-autosuggestions
    clone: yes
    update: yes
  become: true

- name: Copy my custom zshrc file
  copy:
    src: zshrc
    dest: ~/.zshrc
