---
# tasks file for aur
- name: Create aur_builder user
  user:
    name: aur_builder
    group: wheel
  become: yes

- name: Create sudo rights for aur_builder user
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: Install oh-my-zsh via aur
  aur: name=oh-my-zsh-git use=makepkg state=present
  become: yes
  become_user: aur_builder
