---
- name: Install my common packages
  pacman:
    name: 
      - micro
      - latte-dock
      - net-tools
      - vim
      - powerline-fonts
      - xclip
      - brave
    state: latest
  become: true
