---
- name: Install my common packages
  pacman:
    name: 
      - micro
      - latte-dock
      - net-tools
      - vim
      - powerline-fonts
      - xclip
      - brave
      - code
      - docker
      - docker-compose
      - kubectl
      - helm
    state: latest
  become: true
